# models/base.py
class Estimator(Protocol):
    def fit(self, X, y): ...
    def predict(self, X): ...
    def predict_proba(self, X): ...  
    @property
    def feature_names_in_(self) -> list[str]: ...